apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wnh4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wnh4
    app.kubernetes.io/part-of: tkrw-pr712-0075-0019-app
  name: devfile-sample-wnh4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wnh4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wnh4
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0019-tenant/tkrw-pr712-0075-0019-app/devfile-sample-wnh4@sha256:9a3f052dcf88e180ef2222d53053aaf86832fd46ccd7910dc1f459a1150bcf2a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
